### ISSUE TITLE
Práctica 6 Finalizada. Pablo Bethencourt

### ISSUE THREAD

**Issue by alu0100658705** [ULL-ESIT-DSI-1920/dsi-p6-win311-alu0100658705#1]
@ManzDev 

He finalizado la práctica y he realizado los retos 1 y 3.

Muchas gracias. Saludos, Pablo.

**Comment by ManzDev** [comment]
Hola Pablo,

Perfecto. Te ha quedado muy bien.

Faltaría la integración del reto 2 (puedes hacerlo con CustomEvents).
Tienes un APTO en la práctica. Si en algún momento tienes tiempo y quieres ampliarlo y completar el reto 2, me abres el issue de nuevo y mencionas, te lo reviso y te subo a APTO+.

Saludos,
